### ISSUE TITLE
Unicode Error in Windows while using "download" 

### ISSUE THREAD

**Issue by thedirk** [OpenPecha/openpecha-toolkit#11]
error when using command "openpoti download" 

`PS D:\GitHub\Esukhia\openpoti-toolkit> openpoti download -i W1OP000001
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\Scripts\openpoti-script.py", line 11, in <module>
    load_entry_point('openpoti', 'console_scripts', 'openpoti')()
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\github\esukhia\openpoti-toolkit\openpoti\cli.py", line 147, in download
    potis = get_poti(kwargs['id'], kwargs['batch'], kwargs['filter'])
  File "d:\github\esukhia\openpoti-toolkit\openpoti\cli.py", line 71, in get_poti
    catalog_path.write_text(r.content.decode('utf-8'))
  File "c:\users\user\appdata\local\programs\python\python36\lib\pathlib.py", line 1194, in write_text
    return f.write(data)
  File "c:\users\user\appdata\local\programs\python\python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 45-47: character maps to <undefined>`

**Comment by 10zinten** [comment]
Are you able to fix this issue ?
