### ISSUE TITLE
error in a pecha yaml format, crashing the toolkit

### ISSUE THREAD

**Issue by eroux** [OpenPecha/openpecha-toolkit#73]
Unfortunately I can't really know which pecha does this, but I can't import the openpecha in BUDA anymore because of this error when I run the import (after pulling the latest version of the pechas):

```
Converting into rdf:  81%|########################################################################################################################1                            | 3455/4283 [37:29<01:30,  9.16it/s]
Traceback (most recent call last):
  File "/home/admin/.local/bin/openpecha", line 11, in <module>
    load_entry_point('openpecha', 'console_scripts', 'openpecha')()
  File "/home/admin/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/admin/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/admin/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/admin/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/admin/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/admin/openpecha-sync/openpecha-toolkit/openpecha/cli.py", line 418, in cache_to_store
    opm.sync_cache_to_store(store_uri, ldspdi_uri, force, opids)
  File "/home/admin/openpecha-sync/openpecha-toolkit/openpecha/buda/openpecha_manager.py", line 209, in sync_cache_to_store
    if not op.is_ocr():
  File "/home/admin/openpecha-sync/openpecha-toolkit/openpecha/buda/op.py", line 44, in is_ocr
    meta = self.get_meta()
  File "/home/admin/openpecha-sync/openpecha-toolkit/openpecha/buda/op.py", line 40, in get_meta
    self.meta = self.read_meta()
  File "/home/admin/openpecha-sync/openpecha-toolkit/openpecha/buda/op.py", line 35, in read_meta
    return self.read_file_content_yml("meta.yml")
  File "/home/admin/openpecha-sync/openpecha-toolkit/openpecha/buda/op_bare.py", line 30, in read_file_content_yml
    return yaml.safe_load(ymlstr)
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/admin/.local/lib/python3.7/site-packages/yaml/scanner.py", line 260, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 6, column 16:
      publication:      སྡེ་དགེ་པར་ཁང་།
                   ^
```

**Comment by 10zinten** [comment]
Found the Pecha with that issue. It was just YAML syntax error. 
https://github.com/OpenPecha/P000001/blob/5e3898eb13347c7f4832b240dbb42d1f2d7b97f1/P000001.opf/meta.yml#L6

It's fixed now.
